name: build release artifacts

on:
  workflow_dispatch:

jobs:
  build-linux-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: run build
        run: |
          git submodule update --init --recursive
          mkdir build
          cd build && cmake -DCMAKE_BUILD_TYPE=RELEASE ..
          make

      - name: run tests
        run: ./build/test/test_suite

      - name: create release artifacts/packages
        run: |
          cd build
          make package

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-packages
          path: ./build/sqlcheck-x86_64.*

  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: run build
        run: |
          git submodule update --init --recursive
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RELEASE ..
          msbuild ALL_BUILD.vcxproj /t:Build /p:Configuration=Release

      - name: run tests
        run: ./build/test/Release/test_suite.exe

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-packages
          path: ./build/bin/Release/sqlcheck.*
